### ISSUE TITLE
Ручка для Server-Sent-Events о подключении новых игроков в команду

### ISSUE THREAD

**Issue by ChrisBenua** [nekoguys/game-competition#76]
Входные данные: pin игры(аутентификация пользователя)
Выходные данные: поток из элементов вида: {"name": "Имя + email", "isCaptain": boolean}

**Comment by pema4** [comment]
easy, тут надо только в веб-приложение пару функций добавить
в сервисном слое уже всё реализовано

**Comment by pema4** [comment]
Закрываю, вроде как эту задачу сделали. Если не прав - переоткрой issue, пожалуйста
